version: '3'
services:
  backend:
    build: ./
    command: ['rails', 'server', '-b', '0.0.0.0', '-p', '3000']
    container_name: fighting_covid_backend
    depends_on:
      - db
    entrypoint: ['./scripts/docker-entry.sh']
    environment:
      DB_PASSWORD: ${DB_PASSWORD:-localdev}
      RAILS_ENV: ${RAILS_ENV:-development}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES:-false}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    links:
      - db
    ports:
      - '8091:3000'
    stdin_open: true
    tty: true
    volumes:
      - ./:/backend

  db:
    command: ['postgres']
    container_name: fighting_covid_database
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-localdev}
    image: 'postgres:9.6.2'
    ports:
      - '5445:5432'
    volumes:
      - pgdata_117:/var/lib/postgresql/data

volumes:
  pgdata_117: