default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database_url: postgres://postgres:<%= ENV.fetch('DB_PASSWORD') %>@db:5432/fighting_covid_development

test:
  <<: *default
  database_url: postgres://postgres:<%= ENV.fetch('DB_PASSWORD') %>@db:5432/fighting_covid_test

production:
  <<: *default
  database_url: <%= ENV.fetch('DATABASE_URL') %>
