default: &default
  adapter: postgresql
  host: db
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: fighting_covid_development

test:
  <<: *default
  database: fighting_covid_test

production:
  <<: *default
  database: fighting_covid_production
